spring:
  application:
    name: cloud
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  server:
    port: 8082
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 14400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: cn.lmao.cloud.controller
  paths-to-match: /apis/**

file:
  upload:
    path: D:/Cloud/upload